<?php
session_start();
include_once('modele\sqlcheck.php');
include_once('modele\profilemanips.php');
include_once('modele\messagesmanip.php');
include('modele\connexionauto.php');
include_once('modele\starsmanip.php');
include('controleur\bannierehaut.php');
include('controleur\amis.php');
